sonar.organization=rebel-it
sonar.projectKey=rebel-it_rebel-ot-discover-edgeapp

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.Tests/**

sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
